from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

def build_pdf(report_cont):

    # Create a PDF file object
    pdf_filename = "report.pdf"
    doc = SimpleDocTemplate(pdf_filename, pagesize=letter)

    # Get a sample style sheet
    styles = getSampleStyleSheet()

    # Create a story (a sequence of flowable objects)
    story = []
    story.append(Paragraph(report_cont, styles['Normal']))
    story.append(Spacer(1, 12))  # Add some space at the end of the document

    # Build the PDF
    doc.build(story)

    print(f"Report generated and saved as {pdf_filename}")

def build_txt(report_cont):

    # Specify the output text file name
    text_filename = "report.txt"

    # Write the report content to the text file
    with open(text_filename, 'w') as text_file:
        text_file.write(report_cont)

    print(f"Report saved as {text_filename}")

# Variable report_content is a string containing the report generated by Cohere LLM
report_content = "This is the report generated by the LLM AI model. It contains some amazing insights and analysis. AI DETECTIVES! oooooooooooooooooooooooooooooooooooooooooooo ooooooooooooooooooooooooo oooooooooooooooooooooooooooo jjjjjjjjjjjjjjjjjjjjjjjjjjjjj jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn"
file_type = "pdf"

if file_type == "pdf":
    build_pdf(report_content)
else:
    build_txt(report_content)
